### PR TITLE
Add support for fitBounds

### PR DESCRIPTION
**Pull request by echarlus**
Hello,
I've added support for fitBounds through a centerAndZoom method. This is really useful for displaying the map centered & zoomed on a specific area.
It would be great to get this enhancement in the main branch  in a future release.
Thanks !

### CODE REVIEW

**Comment by echarlus** [comment]
Hello, any update on this subject ? Do you see any interest in merging this PR ?
Regards.

**Comment by JohannesRabauer** [comment]
Hi @echarlus,
thanks for your pull-request! Unfortunately this  PR is based on an outdated codebase. I can't merge our updated develop-branch into your PR so you have to do that yourself.
That said: I think the component would be enhanced with your "centerAndZoom"-function. 
Please hold your change with the maven-war-plugin. After this PR is done we will check if an update of the plugin is necessary.

**Review by JohannesRabauer — CHANGES_REQUESTED** [review]
Hi @echarlus,
thanks for your pull-request! Unfortunately this PR is based on an outdated codebase. I can't merge our updated develop-branch into your PR so you have to do that yourself.
That said: I think the component would be enhanced with your "centerAndZoom"-function.
Please hold your change with the maven-war-plugin. After this PR is done we will check if an update of the plugin is necessary.

**Comment by JohannesRabauer** [comment]
Hi @echarlus,
sorry, but i just reviewed the code again and shouldn't be https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/LeafletView.java#L94 exactly what you suggested?

**Comment by echarlus** [comment]
> Hi @echarlus, sorry, but i just reviewed the code again and shouldn't be https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/LeafletView.java#L94 exactly what you suggested?

Hi @JohannesRabauer I'm not sure I understand what you mean here. The code you show is a manual setting of the center & zoom level. The feature I added is to make all this automated and have the map center & zoom level be automatically computed based on the present markers which is really helpful. 
I've not add time to perform the changes you've requested. I'll let you know as soon as I've done it.

**Comment by echarlus** [comment]
@JohannesRabauer I've created a new PR #204 based on latest version, let me know if you're able to merge this one.
Thanks.

**Pull request closed without merging**
