### PR TITLE
 Add support for Leaflet.markercluster

### PR DESCRIPTION
**Pull request by echarlus**
These changes add basic support for [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster).
It enabled Markers clustering and adds an option to customize the cluster's color based on the state of the markers it contains (for example to show that at least one marker is in Error state).
It also adds the API needed to add Tooltips to the Markers.

### CODE REVIEW

**Comment by echarlus** [comment]
Hello @AB-xdev , I'm sorry but I do not know how to fix these Sonar errors as it appears I must have a key that I do not have .. Any idea on how to fix that to give you a chance to review this PR ? 
Thanks

**Comment by AB-xdev** [comment]
@echarlus 

The sonar workflow error likely comes from the missing token, that only we posses, we can check that manually when we review it later.

**Comment by echarlus** [comment]
Hi @AB-xdev any plan on merging the branch to main development branch ? 
Thanks.

**Comment by AB-xdev** [comment]
@echarlus

I got a bit of time now to address #250.

I'm not sure if we should add this feature since I don't know if many people will use it and it requires new JS libraries (that may not be needed by most users).

I think it would be better if we provide this as a separate extension/maven package.

I will clarify how we will go on here internally.

**Comment by AB-xdev** [comment]
We consolidated this topic into #307

Feel free to upvote https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues/307#issuecomment-1842615859

---

I'm closing this PR as we
1. need to consider if there is enough demand for implementing this add-on
2. the PR is no longer compatible with v4

**Comment by AB-xdev** [comment]
From https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues/307#issuecomment-1842633710 (I think the comment was meant for here)

> Hi @AB-xdev thanks for creating this new topic.
> I'm still interested in having the merge done and I'm willing to make the changes to the P.R in order for them to work with the latest version.
> Let me know when you've made your decision.
> Thanks.

**Pull request closed without merging**
